# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tunight - 金枪鱼之夜
email: scateu@gmail.com
owner: TUNA
author: TUNA
copyright: Tsinghua University TUNA Association
description: 金枪鱼之夜
baseurl: "" # the subpath of your site, e.g. /blog
category: Technology

url: "http://podcast.tuna.moe" # the base hostname & protocol for your site
default_thumb: "http://podcast.tuna.moe/assets/img/tuna.png"

# Build settings
markdown: kramdown

about: "清华大学 TUNA 协会原名清华大学学生网管会，其前身为清华大学电脑协会，是由清华大学网络技术和开源软件爱好者、技术宅组成的团体。"
